%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1
%% Version source: git
-module(ext_master_proto).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).


%% enumerated types

-export_type([]).

%% message types
-type 'master.Address'() ::
      #{replica                 => unicode:chardata(), % = 1, optional
        partition               => non_neg_integer(), % = 2, optional, 32 bits
        ip                      => unicode:chardata(), % = 3, optional
        port                    => non_neg_integer() % = 4, optional, 32 bits
       }.

-type 'master.Register'() ::
      #{replicaId               => unicode:chardata(), % = 1, optional
        ip                      => unicode:chardata(), % = 2, optional
        localPort               => non_neg_integer(), % = 3, optional, 32 bits
        remotePort              => non_neg_integer() % = 4, optional, 32 bits
       }.

-type 'master.RegisterReply'() ::
      #{partition               => non_neg_integer(), % = 1, optional, 32 bits
        leader                  => 'master.Address'(), % = 2, optional
        siblings                => ['master.Address'()], % = 3, repeated
        localNodes              => ['master.Address'()] % = 4, repeated
       }.

-type 'master.GetNodesReply'() ::
      #{nodes                   => ['master.Address'()] % = 1, repeated
       }.

-type 'master.Request'() ::
      #{seq                     => non_neg_integer(), % = 1, optional, 32 bits
        payload                 => {registerNode, 'master.Register'()} | {getPartitionLeader, non_neg_integer()} | {getReplicaNodes, unicode:chardata()} % oneof
       }.

-type 'master.Response'() ::
      #{seq                     => non_neg_integer(), % = 1, optional, 32 bits
        payload                 => {registerReply, 'master.RegisterReply'()} | {getPartitionLeaderReply, 'master.Address'()} | {getReplicaNodesReply, 'master.GetNodesReply'()} % oneof
       }.

-export_type(['master.Address'/0, 'master.Register'/0, 'master.RegisterReply'/0, 'master.GetNodesReply'/0, 'master.Request'/0, 'master.Response'/0]).
-type '$msg_name'() :: 'master.Address' | 'master.Register' | 'master.RegisterReply' | 'master.GetNodesReply' | 'master.Request' | 'master.Response'.
-type '$msg'() :: 'master.Address'() | 'master.Register'() | 'master.RegisterReply'() | 'master.GetNodesReply'() | 'master.Request'() | 'master.Response'().
-export_type(['$msg_name'/0, '$msg'/0]).

-dialyzer({no_underspecs, encode_msg/2}).
-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-dialyzer({no_underspecs, encode_msg/3}).
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'master.Address' -> 'encode_msg_master.Address'(id(Msg, TrUserData), TrUserData);
        'master.Register' -> 'encode_msg_master.Register'(id(Msg, TrUserData), TrUserData);
        'master.RegisterReply' -> 'encode_msg_master.RegisterReply'(id(Msg, TrUserData), TrUserData);
        'master.GetNodesReply' -> 'encode_msg_master.GetNodesReply'(id(Msg, TrUserData), TrUserData);
        'master.Request' -> 'encode_msg_master.Request'(id(Msg, TrUserData), TrUserData);
        'master.Response' -> 'encode_msg_master.Response'(id(Msg, TrUserData), TrUserData)
    end.


'encode_msg_master.Address'(Msg, TrUserData) -> 'encode_msg_master.Address'(Msg, <<>>, TrUserData).


'encode_msg_master.Address'(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{replica := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{partition := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     if TrF2 =:= 0 -> B1;
                        true -> e_varint(TrF2, <<B1/binary, 16>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{ip := F3} ->
                 begin
                     TrF3 = id(F3, TrUserData),
                     case is_empty_string(TrF3) of
                         true -> B2;
                         false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
                     end
                 end;
             _ -> B2
         end,
    case M of
        #{port := F4} ->
            begin
                TrF4 = id(F4, TrUserData),
                if TrF4 =:= 0 -> B3;
                   true -> e_varint(TrF4, <<B3/binary, 32>>, TrUserData)
                end
            end;
        _ -> B3
    end.

'encode_msg_master.Register'(Msg, TrUserData) -> 'encode_msg_master.Register'(Msg, <<>>, TrUserData).


'encode_msg_master.Register'(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{replicaId := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{ip := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     case is_empty_string(TrF2) of
                         true -> B1;
                         false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{localPort := F3} ->
                 begin
                     TrF3 = id(F3, TrUserData),
                     if TrF3 =:= 0 -> B2;
                        true -> e_varint(TrF3, <<B2/binary, 24>>, TrUserData)
                     end
                 end;
             _ -> B2
         end,
    case M of
        #{remotePort := F4} ->
            begin
                TrF4 = id(F4, TrUserData),
                if TrF4 =:= 0 -> B3;
                   true -> e_varint(TrF4, <<B3/binary, 32>>, TrUserData)
                end
            end;
        _ -> B3
    end.

'encode_msg_master.RegisterReply'(Msg, TrUserData) -> 'encode_msg_master.RegisterReply'(Msg, <<>>, TrUserData).


'encode_msg_master.RegisterReply'(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{partition := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= 0 -> Bin;
                        true -> e_varint(TrF1, <<Bin/binary, 8>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{leader := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     if TrF2 =:= undefined -> B1;
                        true -> 'e_mfield_master.RegisterReply_leader'(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{siblings := F3} ->
                 TrF3 = id(F3, TrUserData),
                 if TrF3 == [] -> B2;
                    true -> 'e_field_master.RegisterReply_siblings'(TrF3, B2, TrUserData)
                 end;
             _ -> B2
         end,
    case M of
        #{localNodes := F4} ->
            TrF4 = id(F4, TrUserData),
            if TrF4 == [] -> B3;
               true -> 'e_field_master.RegisterReply_localNodes'(TrF4, B3, TrUserData)
            end;
        _ -> B3
    end.

'encode_msg_master.GetNodesReply'(Msg, TrUserData) -> 'encode_msg_master.GetNodesReply'(Msg, <<>>, TrUserData).


'encode_msg_master.GetNodesReply'(#{} = M, Bin, TrUserData) ->
    case M of
        #{nodes := F1} ->
            TrF1 = id(F1, TrUserData),
            if TrF1 == [] -> Bin;
               true -> 'e_field_master.GetNodesReply_nodes'(TrF1, Bin, TrUserData)
            end;
        _ -> Bin
    end.

'encode_msg_master.Request'(Msg, TrUserData) -> 'encode_msg_master.Request'(Msg, <<>>, TrUserData).


'encode_msg_master.Request'(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{seq := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= 0 -> Bin;
                        true -> e_varint(TrF1, <<Bin/binary, 8>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{payload := F2} ->
            case id(F2, TrUserData) of
                {registerNode, TF2} -> begin TrTF2 = id(TF2, TrUserData), 'e_mfield_master.Request_registerNode'(TrTF2, <<B1/binary, 18>>, TrUserData) end;
                {getPartitionLeader, TF2} -> begin TrTF2 = id(TF2, TrUserData), e_varint(TrTF2, <<B1/binary, 24>>, TrUserData) end;
                {getReplicaNodes, TF2} -> begin TrTF2 = id(TF2, TrUserData), e_type_string(TrTF2, <<B1/binary, 34>>, TrUserData) end
            end;
        _ -> B1
    end.

'encode_msg_master.Response'(Msg, TrUserData) -> 'encode_msg_master.Response'(Msg, <<>>, TrUserData).


'encode_msg_master.Response'(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{seq := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= 0 -> Bin;
                        true -> e_varint(TrF1, <<Bin/binary, 8>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{payload := F2} ->
            case id(F2, TrUserData) of
                {registerReply, TF2} -> begin TrTF2 = id(TF2, TrUserData), 'e_mfield_master.Response_registerReply'(TrTF2, <<B1/binary, 18>>, TrUserData) end;
                {getPartitionLeaderReply, TF2} -> begin TrTF2 = id(TF2, TrUserData), 'e_mfield_master.Response_getPartitionLeaderReply'(TrTF2, <<B1/binary, 26>>, TrUserData) end;
                {getReplicaNodesReply, TF2} -> begin TrTF2 = id(TF2, TrUserData), 'e_mfield_master.Response_getReplicaNodesReply'(TrTF2, <<B1/binary, 34>>, TrUserData) end
            end;
        _ -> B1
    end.

'e_mfield_master.RegisterReply_leader'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.Address'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_mfield_master.RegisterReply_siblings'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.Address'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_field_master.RegisterReply_siblings'([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 26>>,
    Bin3 = 'e_mfield_master.RegisterReply_siblings'(id(Elem, TrUserData), Bin2, TrUserData),
    'e_field_master.RegisterReply_siblings'(Rest, Bin3, TrUserData);
'e_field_master.RegisterReply_siblings'([], Bin, _TrUserData) -> Bin.

'e_mfield_master.RegisterReply_localNodes'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.Address'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_field_master.RegisterReply_localNodes'([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 34>>,
    Bin3 = 'e_mfield_master.RegisterReply_localNodes'(id(Elem, TrUserData), Bin2, TrUserData),
    'e_field_master.RegisterReply_localNodes'(Rest, Bin3, TrUserData);
'e_field_master.RegisterReply_localNodes'([], Bin, _TrUserData) -> Bin.

'e_mfield_master.GetNodesReply_nodes'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.Address'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_field_master.GetNodesReply_nodes'([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = 'e_mfield_master.GetNodesReply_nodes'(id(Elem, TrUserData), Bin2, TrUserData),
    'e_field_master.GetNodesReply_nodes'(Rest, Bin3, TrUserData);
'e_field_master.GetNodesReply_nodes'([], Bin, _TrUserData) -> Bin.

'e_mfield_master.Request_registerNode'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.Register'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_mfield_master.Response_registerReply'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.RegisterReply'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_mfield_master.Response_getPartitionLeaderReply'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.Address'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_mfield_master.Response_getReplicaNodesReply'(Msg, Bin, TrUserData) ->
    SubBin = 'encode_msg_master.GetNodesReply'(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('master.Address', Bin, TrUserData) -> id('decode_msg_master.Address'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('master.Register', Bin, TrUserData) -> id('decode_msg_master.Register'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('master.RegisterReply', Bin, TrUserData) -> id('decode_msg_master.RegisterReply'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('master.GetNodesReply', Bin, TrUserData) -> id('decode_msg_master.GetNodesReply'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('master.Request', Bin, TrUserData) -> id('decode_msg_master.Request'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('master.Response', Bin, TrUserData) -> id('decode_msg_master.Response'(Bin, TrUserData), TrUserData).



'decode_msg_master.Address'(Bin, TrUserData) -> 'dfp_read_field_def_master.Address'(Bin, 0, 0, 0, id(<<>>, TrUserData), id(0, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), TrUserData).

'dfp_read_field_def_master.Address'(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Address_replica'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Address'(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Address_partition'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Address'(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Address_ip'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Address'(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Address_port'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Address'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #{replica => F@_1, partition => F@_2, ip => F@_3, port => F@_4};
'dfp_read_field_def_master.Address'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dg_read_field_def_master.Address'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'dg_read_field_def_master.Address'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_master.Address'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dg_read_field_def_master.Address'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> 'd_field_master.Address_replica'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        16 -> 'd_field_master.Address_partition'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        26 -> 'd_field_master.Address_ip'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        32 -> 'd_field_master.Address_port'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_master.Address'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> 'skip_64_master.Address'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> 'skip_length_delimited_master.Address'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> 'skip_group_master.Address'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> 'skip_32_master.Address'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
'dg_read_field_def_master.Address'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #{replica => F@_1, partition => F@_2, ip => F@_3, port => F@_4}.

'd_field_master.Address_replica'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Address_replica'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Address_replica'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_master.Address'(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

'd_field_master.Address_partition'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Address_partition'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Address_partition'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Address'(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

'd_field_master.Address_ip'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Address_ip'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Address_ip'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_master.Address'(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

'd_field_master.Address_port'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Address_port'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Address_port'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Address'(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData).

'skip_varint_master.Address'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'skip_varint_master.Address'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'skip_varint_master.Address'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.Address'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_length_delimited_master.Address'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'skip_length_delimited_master.Address'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'skip_length_delimited_master.Address'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_master.Address'(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_group_master.Address'(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_master.Address'(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_32_master.Address'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.Address'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_64_master.Address'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.Address'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'decode_msg_master.Register'(Bin, TrUserData) -> 'dfp_read_field_def_master.Register'(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id(0, TrUserData), TrUserData).

'dfp_read_field_def_master.Register'(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Register_replicaId'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Register'(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Register_ip'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Register'(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Register_localPort'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Register'(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.Register_remotePort'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.Register'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #{replicaId => F@_1, ip => F@_2, localPort => F@_3, remotePort => F@_4};
'dfp_read_field_def_master.Register'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dg_read_field_def_master.Register'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'dg_read_field_def_master.Register'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_master.Register'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dg_read_field_def_master.Register'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> 'd_field_master.Register_replicaId'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        18 -> 'd_field_master.Register_ip'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        24 -> 'd_field_master.Register_localPort'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        32 -> 'd_field_master.Register_remotePort'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_master.Register'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> 'skip_64_master.Register'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> 'skip_length_delimited_master.Register'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> 'skip_group_master.Register'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> 'skip_32_master.Register'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
'dg_read_field_def_master.Register'(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #{replicaId => F@_1, ip => F@_2, localPort => F@_3, remotePort => F@_4}.

'd_field_master.Register_replicaId'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Register_replicaId'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Register_replicaId'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_master.Register'(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

'd_field_master.Register_ip'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Register_ip'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Register_ip'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_master.Register'(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

'd_field_master.Register_localPort'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Register_localPort'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Register_localPort'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Register'(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

'd_field_master.Register_remotePort'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.Register_remotePort'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.Register_remotePort'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Register'(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData).

'skip_varint_master.Register'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'skip_varint_master.Register'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'skip_varint_master.Register'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.Register'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_length_delimited_master.Register'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'skip_length_delimited_master.Register'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'skip_length_delimited_master.Register'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_master.Register'(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_group_master.Register'(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_master.Register'(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_32_master.Register'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.Register'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_64_master.Register'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.Register'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'decode_msg_master.RegisterReply'(Bin, TrUserData) -> 'dfp_read_field_def_master.RegisterReply'(Bin, 0, 0, 0, id(0, TrUserData), id('$undef', TrUserData), id([], TrUserData), id([], TrUserData), TrUserData).

'dfp_read_field_def_master.RegisterReply'(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.RegisterReply_partition'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.RegisterReply'(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.RegisterReply_leader'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.RegisterReply'(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.RegisterReply_siblings'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.RegisterReply'(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'd_field_master.RegisterReply_localNodes'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dfp_read_field_def_master.RegisterReply'(<<>>, 0, 0, _, F@_1, F@_2, R1, R2, TrUserData) ->
    S1 = #{partition => F@_1},
    S2 = if F@_2 == '$undef' -> S1;
            true -> S1#{leader => F@_2}
         end,
    S3 = if R1 == '$undef' -> S2;
            true -> S2#{siblings => lists_reverse(R1, TrUserData)}
         end,
    if R2 == '$undef' -> S3;
       true -> S3#{localNodes => lists_reverse(R2, TrUserData)}
    end;
'dfp_read_field_def_master.RegisterReply'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dg_read_field_def_master.RegisterReply'(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'dg_read_field_def_master.RegisterReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_master.RegisterReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'dg_read_field_def_master.RegisterReply'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> 'd_field_master.RegisterReply_partition'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        18 -> 'd_field_master.RegisterReply_leader'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        26 -> 'd_field_master.RegisterReply_siblings'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        34 -> 'd_field_master.RegisterReply_localNodes'(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_master.RegisterReply'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> 'skip_64_master.RegisterReply'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> 'skip_length_delimited_master.RegisterReply'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> 'skip_group_master.RegisterReply'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> 'skip_32_master.RegisterReply'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
'dg_read_field_def_master.RegisterReply'(<<>>, 0, 0, _, F@_1, F@_2, R1, R2, TrUserData) ->
    S1 = #{partition => F@_1},
    S2 = if F@_2 == '$undef' -> S1;
            true -> S1#{leader => F@_2}
         end,
    S3 = if R1 == '$undef' -> S2;
            true -> S2#{siblings => lists_reverse(R1, TrUserData)}
         end,
    if R2 == '$undef' -> S3;
       true -> S3#{localNodes => lists_reverse(R2, TrUserData)}
    end.

'd_field_master.RegisterReply_partition'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.RegisterReply_partition'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.RegisterReply_partition'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.RegisterReply'(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

'd_field_master.RegisterReply_leader'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.RegisterReply_leader'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.RegisterReply_leader'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.Address'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.RegisterReply'(RestF,
                                              0,
                                              0,
                                              F,
                                              F@_1,
                                              if Prev == '$undef' -> NewFValue;
                                                 true -> 'merge_msg_master.Address'(Prev, NewFValue, TrUserData)
                                              end,
                                              F@_3,
                                              F@_4,
                                              TrUserData).

'd_field_master.RegisterReply_siblings'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.RegisterReply_siblings'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.RegisterReply_siblings'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, Prev, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.Address'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.RegisterReply'(RestF, 0, 0, F, F@_1, F@_2, cons(NewFValue, Prev, TrUserData), F@_4, TrUserData).

'd_field_master.RegisterReply_localNodes'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'd_field_master.RegisterReply_localNodes'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'd_field_master.RegisterReply_localNodes'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.Address'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.RegisterReply'(RestF, 0, 0, F, F@_1, F@_2, F@_3, cons(NewFValue, Prev, TrUserData), TrUserData).

'skip_varint_master.RegisterReply'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'skip_varint_master.RegisterReply'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'skip_varint_master.RegisterReply'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.RegisterReply'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_length_delimited_master.RegisterReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> 'skip_length_delimited_master.RegisterReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
'skip_length_delimited_master.RegisterReply'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_master.RegisterReply'(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_group_master.RegisterReply'(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_master.RegisterReply'(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_32_master.RegisterReply'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.RegisterReply'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'skip_64_master.RegisterReply'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> 'dfp_read_field_def_master.RegisterReply'(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

'decode_msg_master.GetNodesReply'(Bin, TrUserData) -> 'dfp_read_field_def_master.GetNodesReply'(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

'dfp_read_field_def_master.GetNodesReply'(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> 'd_field_master.GetNodesReply_nodes'(Rest, Z1, Z2, F, F@_1, TrUserData);
'dfp_read_field_def_master.GetNodesReply'(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{nodes => lists_reverse(R1, TrUserData)}
    end;
'dfp_read_field_def_master.GetNodesReply'(Other, Z1, Z2, F, F@_1, TrUserData) -> 'dg_read_field_def_master.GetNodesReply'(Other, Z1, Z2, F, F@_1, TrUserData).

'dg_read_field_def_master.GetNodesReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_master.GetNodesReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
'dg_read_field_def_master.GetNodesReply'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> 'd_field_master.GetNodesReply_nodes'(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_master.GetNodesReply'(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> 'skip_64_master.GetNodesReply'(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> 'skip_length_delimited_master.GetNodesReply'(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> 'skip_group_master.GetNodesReply'(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> 'skip_32_master.GetNodesReply'(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
'dg_read_field_def_master.GetNodesReply'(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{nodes => lists_reverse(R1, TrUserData)}
    end.

'd_field_master.GetNodesReply_nodes'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> 'd_field_master.GetNodesReply_nodes'(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
'd_field_master.GetNodesReply_nodes'(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.Address'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.GetNodesReply'(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

'skip_varint_master.GetNodesReply'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> 'skip_varint_master.GetNodesReply'(Rest, Z1, Z2, F, F@_1, TrUserData);
'skip_varint_master.GetNodesReply'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> 'dfp_read_field_def_master.GetNodesReply'(Rest, Z1, Z2, F, F@_1, TrUserData).

'skip_length_delimited_master.GetNodesReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> 'skip_length_delimited_master.GetNodesReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
'skip_length_delimited_master.GetNodesReply'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_master.GetNodesReply'(Rest2, 0, 0, F, F@_1, TrUserData).

'skip_group_master.GetNodesReply'(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_master.GetNodesReply'(Rest, 0, Z2, FNum, F@_1, TrUserData).

'skip_32_master.GetNodesReply'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> 'dfp_read_field_def_master.GetNodesReply'(Rest, Z1, Z2, F, F@_1, TrUserData).

'skip_64_master.GetNodesReply'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> 'dfp_read_field_def_master.GetNodesReply'(Rest, Z1, Z2, F, F@_1, TrUserData).

'decode_msg_master.Request'(Bin, TrUserData) -> 'dfp_read_field_def_master.Request'(Bin, 0, 0, 0, id(0, TrUserData), id('$undef', TrUserData), TrUserData).

'dfp_read_field_def_master.Request'(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Request_seq'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Request'(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Request_registerNode'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Request'(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Request_getPartitionLeader'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Request'(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Request_getReplicaNodes'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Request'(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{seq => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{payload => F@_2}
    end;
'dfp_read_field_def_master.Request'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dg_read_field_def_master.Request'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

'dg_read_field_def_master.Request'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_master.Request'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'dg_read_field_def_master.Request'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> 'd_field_master.Request_seq'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> 'd_field_master.Request_registerNode'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        24 -> 'd_field_master.Request_getPartitionLeader'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        34 -> 'd_field_master.Request_getReplicaNodes'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_master.Request'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> 'skip_64_master.Request'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> 'skip_length_delimited_master.Request'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> 'skip_group_master.Request'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> 'skip_32_master.Request'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
'dg_read_field_def_master.Request'(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{seq => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{payload => F@_2}
    end.

'd_field_master.Request_seq'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Request_seq'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Request_seq'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Request'(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

'd_field_master.Request_registerNode'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Request_registerNode'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Request_registerNode'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.Register'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.Request'(RestF,
                                        0,
                                        0,
                                        F,
                                        F@_1,
                                        case Prev of
                                            '$undef' -> id({registerNode, NewFValue}, TrUserData);
                                            {registerNode, MVPrev} -> id({registerNode, 'merge_msg_master.Register'(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                            _ -> id({registerNode, NewFValue}, TrUserData)
                                        end,
                                        TrUserData).

'd_field_master.Request_getPartitionLeader'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Request_getPartitionLeader'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Request_getPartitionLeader'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Request'(RestF, 0, 0, F, F@_1, id({getPartitionLeader, NewFValue}, TrUserData), TrUserData).

'd_field_master.Request_getReplicaNodes'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Request_getReplicaNodes'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Request_getReplicaNodes'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    'dfp_read_field_def_master.Request'(RestF, 0, 0, F, F@_1, id({getReplicaNodes, NewFValue}, TrUserData), TrUserData).

'skip_varint_master.Request'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'skip_varint_master.Request'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'skip_varint_master.Request'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_master.Request'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_length_delimited_master.Request'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'skip_length_delimited_master.Request'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'skip_length_delimited_master.Request'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_master.Request'(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

'skip_group_master.Request'(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_master.Request'(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

'skip_32_master.Request'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_master.Request'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_64_master.Request'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_master.Request'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'decode_msg_master.Response'(Bin, TrUserData) -> 'dfp_read_field_def_master.Response'(Bin, 0, 0, 0, id(0, TrUserData), id('$undef', TrUserData), TrUserData).

'dfp_read_field_def_master.Response'(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Response_seq'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Response'(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Response_registerReply'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Response'(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Response_getPartitionLeaderReply'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Response'(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_master.Response_getReplicaNodesReply'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_master.Response'(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{seq => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{payload => F@_2}
    end;
'dfp_read_field_def_master.Response'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dg_read_field_def_master.Response'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

'dg_read_field_def_master.Response'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_master.Response'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'dg_read_field_def_master.Response'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> 'd_field_master.Response_seq'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> 'd_field_master.Response_registerReply'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        26 -> 'd_field_master.Response_getPartitionLeaderReply'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        34 -> 'd_field_master.Response_getReplicaNodesReply'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> 'skip_varint_master.Response'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> 'skip_64_master.Response'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> 'skip_length_delimited_master.Response'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> 'skip_group_master.Response'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> 'skip_32_master.Response'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
'dg_read_field_def_master.Response'(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{seq => F@_1},
    if F@_2 == '$undef' -> S1;
       true -> S1#{payload => F@_2}
    end.

'd_field_master.Response_seq'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Response_seq'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Response_seq'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    'dfp_read_field_def_master.Response'(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

'd_field_master.Response_registerReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Response_registerReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Response_registerReply'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.RegisterReply'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.Response'(RestF,
                                         0,
                                         0,
                                         F,
                                         F@_1,
                                         case Prev of
                                             '$undef' -> id({registerReply, NewFValue}, TrUserData);
                                             {registerReply, MVPrev} -> id({registerReply, 'merge_msg_master.RegisterReply'(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                             _ -> id({registerReply, NewFValue}, TrUserData)
                                         end,
                                         TrUserData).

'd_field_master.Response_getPartitionLeaderReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Response_getPartitionLeaderReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Response_getPartitionLeaderReply'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.Address'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.Response'(RestF,
                                         0,
                                         0,
                                         F,
                                         F@_1,
                                         case Prev of
                                             '$undef' -> id({getPartitionLeaderReply, NewFValue}, TrUserData);
                                             {getPartitionLeaderReply, MVPrev} -> id({getPartitionLeaderReply, 'merge_msg_master.Address'(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                             _ -> id({getPartitionLeaderReply, NewFValue}, TrUserData)
                                         end,
                                         TrUserData).

'd_field_master.Response_getReplicaNodesReply'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_master.Response_getReplicaNodesReply'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_master.Response_getReplicaNodesReply'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_master.GetNodesReply'(Bs, TrUserData), TrUserData), Rest2} end,
    'dfp_read_field_def_master.Response'(RestF,
                                         0,
                                         0,
                                         F,
                                         F@_1,
                                         case Prev of
                                             '$undef' -> id({getReplicaNodesReply, NewFValue}, TrUserData);
                                             {getReplicaNodesReply, MVPrev} -> id({getReplicaNodesReply, 'merge_msg_master.GetNodesReply'(MVPrev, NewFValue, TrUserData)}, TrUserData);
                                             _ -> id({getReplicaNodesReply, NewFValue}, TrUserData)
                                         end,
                                         TrUserData).

'skip_varint_master.Response'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'skip_varint_master.Response'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'skip_varint_master.Response'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_master.Response'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_length_delimited_master.Response'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'skip_length_delimited_master.Response'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'skip_length_delimited_master.Response'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    'dfp_read_field_def_master.Response'(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

'skip_group_master.Response'(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    'dfp_read_field_def_master.Response'(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

'skip_32_master.Response'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_master.Response'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_64_master.Response'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_master.Response'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'master.Address' -> 'merge_msg_master.Address'(Prev, New, TrUserData);
        'master.Register' -> 'merge_msg_master.Register'(Prev, New, TrUserData);
        'master.RegisterReply' -> 'merge_msg_master.RegisterReply'(Prev, New, TrUserData);
        'master.GetNodesReply' -> 'merge_msg_master.GetNodesReply'(Prev, New, TrUserData);
        'master.Request' -> 'merge_msg_master.Request'(Prev, New, TrUserData);
        'master.Response' -> 'merge_msg_master.Response'(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,'merge_msg_master.Address'/3}).
'merge_msg_master.Address'(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{replica := NFreplica}} -> S1#{replica => NFreplica};
             {#{replica := PFreplica}, _} -> S1#{replica => PFreplica};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{partition := NFpartition}} -> S2#{partition => NFpartition};
             {#{partition := PFpartition}, _} -> S2#{partition => PFpartition};
             _ -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {_, #{ip := NFip}} -> S3#{ip => NFip};
             {#{ip := PFip}, _} -> S3#{ip => PFip};
             _ -> S3
         end,
    case {PMsg, NMsg} of
        {_, #{port := NFport}} -> S4#{port => NFport};
        {#{port := PFport}, _} -> S4#{port => PFport};
        _ -> S4
    end.

-compile({nowarn_unused_function,'merge_msg_master.Register'/3}).
'merge_msg_master.Register'(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{replicaId := NFreplicaId}} -> S1#{replicaId => NFreplicaId};
             {#{replicaId := PFreplicaId}, _} -> S1#{replicaId => PFreplicaId};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{ip := NFip}} -> S2#{ip => NFip};
             {#{ip := PFip}, _} -> S2#{ip => PFip};
             _ -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {_, #{localPort := NFlocalPort}} -> S3#{localPort => NFlocalPort};
             {#{localPort := PFlocalPort}, _} -> S3#{localPort => PFlocalPort};
             _ -> S3
         end,
    case {PMsg, NMsg} of
        {_, #{remotePort := NFremotePort}} -> S4#{remotePort => NFremotePort};
        {#{remotePort := PFremotePort}, _} -> S4#{remotePort => PFremotePort};
        _ -> S4
    end.

-compile({nowarn_unused_function,'merge_msg_master.RegisterReply'/3}).
'merge_msg_master.RegisterReply'(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{partition := NFpartition}} -> S1#{partition => NFpartition};
             {#{partition := PFpartition}, _} -> S1#{partition => PFpartition};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {#{leader := PFleader}, #{leader := NFleader}} -> S2#{leader => 'merge_msg_master.Address'(PFleader, NFleader, TrUserData)};
             {_, #{leader := NFleader}} -> S2#{leader => NFleader};
             {#{leader := PFleader}, _} -> S2#{leader => PFleader};
             {_, _} -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {#{siblings := PFsiblings}, #{siblings := NFsiblings}} -> S3#{siblings => 'erlang_++'(PFsiblings, NFsiblings, TrUserData)};
             {_, #{siblings := NFsiblings}} -> S3#{siblings => NFsiblings};
             {#{siblings := PFsiblings}, _} -> S3#{siblings => PFsiblings};
             {_, _} -> S3
         end,
    case {PMsg, NMsg} of
        {#{localNodes := PFlocalNodes}, #{localNodes := NFlocalNodes}} -> S4#{localNodes => 'erlang_++'(PFlocalNodes, NFlocalNodes, TrUserData)};
        {_, #{localNodes := NFlocalNodes}} -> S4#{localNodes => NFlocalNodes};
        {#{localNodes := PFlocalNodes}, _} -> S4#{localNodes => PFlocalNodes};
        {_, _} -> S4
    end.

-compile({nowarn_unused_function,'merge_msg_master.GetNodesReply'/3}).
'merge_msg_master.GetNodesReply'(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{nodes := PFnodes}, #{nodes := NFnodes}} -> S1#{nodes => 'erlang_++'(PFnodes, NFnodes, TrUserData)};
        {_, #{nodes := NFnodes}} -> S1#{nodes => NFnodes};
        {#{nodes := PFnodes}, _} -> S1#{nodes => PFnodes};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,'merge_msg_master.Request'/3}).
'merge_msg_master.Request'(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{seq := NFseq}} -> S1#{seq => NFseq};
             {#{seq := PFseq}, _} -> S1#{seq => PFseq};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {#{payload := {registerNode, OPFpayload}}, #{payload := {registerNode, ONFpayload}}} -> S2#{payload => {registerNode, 'merge_msg_master.Register'(OPFpayload, ONFpayload, TrUserData)}};
        {_, #{payload := NFpayload}} -> S2#{payload => NFpayload};
        {#{payload := PFpayload}, _} -> S2#{payload => PFpayload};
        {_, _} -> S2
    end.

-compile({nowarn_unused_function,'merge_msg_master.Response'/3}).
'merge_msg_master.Response'(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{seq := NFseq}} -> S1#{seq => NFseq};
             {#{seq := PFseq}, _} -> S1#{seq => PFseq};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {#{payload := {registerReply, OPFpayload}}, #{payload := {registerReply, ONFpayload}}} -> S2#{payload => {registerReply, 'merge_msg_master.RegisterReply'(OPFpayload, ONFpayload, TrUserData)}};
        {#{payload := {getPartitionLeaderReply, OPFpayload}}, #{payload := {getPartitionLeaderReply, ONFpayload}}} -> S2#{payload => {getPartitionLeaderReply, 'merge_msg_master.Address'(OPFpayload, ONFpayload, TrUserData)}};
        {#{payload := {getReplicaNodesReply, OPFpayload}}, #{payload := {getReplicaNodesReply, ONFpayload}}} -> S2#{payload => {getReplicaNodesReply, 'merge_msg_master.GetNodesReply'(OPFpayload, ONFpayload, TrUserData)}};
        {_, #{payload := NFpayload}} -> S2#{payload => NFpayload};
        {#{payload := PFpayload}, _} -> S2#{payload => PFpayload};
        {_, _} -> S2
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'master.Address' -> 'v_msg_master.Address'(Msg, [MsgName], TrUserData);
        'master.Register' -> 'v_msg_master.Register'(Msg, [MsgName], TrUserData);
        'master.RegisterReply' -> 'v_msg_master.RegisterReply'(Msg, [MsgName], TrUserData);
        'master.GetNodesReply' -> 'v_msg_master.GetNodesReply'(Msg, [MsgName], TrUserData);
        'master.Request' -> 'v_msg_master.Request'(Msg, [MsgName], TrUserData);
        'master.Response' -> 'v_msg_master.Response'(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,'v_msg_master.Address'/3}).
-dialyzer({nowarn_function,'v_msg_master.Address'/3}).
'v_msg_master.Address'(#{} = M, Path, TrUserData) ->
    case M of
        #{replica := F1} -> v_type_string(F1, [replica | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{partition := F2} -> v_type_uint32(F2, [partition | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{ip := F3} -> v_type_string(F3, [ip | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{port := F4} -> v_type_uint32(F4, [port | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (replica) -> ok;
                      (partition) -> ok;
                      (ip) -> ok;
                      (port) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
'v_msg_master.Address'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'master.Address'}, M, Path);
'v_msg_master.Address'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'master.Address'}, X, Path).

-compile({nowarn_unused_function,'v_msg_master.Register'/3}).
-dialyzer({nowarn_function,'v_msg_master.Register'/3}).
'v_msg_master.Register'(#{} = M, Path, TrUserData) ->
    case M of
        #{replicaId := F1} -> v_type_string(F1, [replicaId | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{ip := F2} -> v_type_string(F2, [ip | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{localPort := F3} -> v_type_uint32(F3, [localPort | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{remotePort := F4} -> v_type_uint32(F4, [remotePort | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (replicaId) -> ok;
                      (ip) -> ok;
                      (localPort) -> ok;
                      (remotePort) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
'v_msg_master.Register'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'master.Register'}, M, Path);
'v_msg_master.Register'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'master.Register'}, X, Path).

-compile({nowarn_unused_function,'v_msg_master.RegisterReply'/3}).
-dialyzer({nowarn_function,'v_msg_master.RegisterReply'/3}).
'v_msg_master.RegisterReply'(#{} = M, Path, TrUserData) ->
    case M of
        #{partition := F1} -> v_type_uint32(F1, [partition | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{leader := F2} -> 'v_msg_master.Address'(F2, [leader | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{siblings := F3} ->
            if is_list(F3) ->
                   _ = ['v_msg_master.Address'(Elem, [siblings | Path], TrUserData) || Elem <- F3],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, 'master.Address'}}, F3, [siblings | Path])
            end;
        _ -> ok
    end,
    case M of
        #{localNodes := F4} ->
            if is_list(F4) ->
                   _ = ['v_msg_master.Address'(Elem, [localNodes | Path], TrUserData) || Elem <- F4],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, 'master.Address'}}, F4, [localNodes | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (partition) -> ok;
                      (leader) -> ok;
                      (siblings) -> ok;
                      (localNodes) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
'v_msg_master.RegisterReply'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'master.RegisterReply'}, M, Path);
'v_msg_master.RegisterReply'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'master.RegisterReply'}, X, Path).

-compile({nowarn_unused_function,'v_msg_master.GetNodesReply'/3}).
-dialyzer({nowarn_function,'v_msg_master.GetNodesReply'/3}).
'v_msg_master.GetNodesReply'(#{} = M, Path, TrUserData) ->
    case M of
        #{nodes := F1} ->
            if is_list(F1) ->
                   _ = ['v_msg_master.Address'(Elem, [nodes | Path], TrUserData) || Elem <- F1],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, 'master.Address'}}, F1, [nodes | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (nodes) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
'v_msg_master.GetNodesReply'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'master.GetNodesReply'}, M, Path);
'v_msg_master.GetNodesReply'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'master.GetNodesReply'}, X, Path).

-compile({nowarn_unused_function,'v_msg_master.Request'/3}).
-dialyzer({nowarn_function,'v_msg_master.Request'/3}).
'v_msg_master.Request'(#{} = M, Path, TrUserData) ->
    case M of
        #{seq := F1} -> v_type_uint32(F1, [seq | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{payload := {registerNode, OF2}} -> 'v_msg_master.Register'(OF2, [registerNode, payload | Path], TrUserData);
        #{payload := {getPartitionLeader, OF2}} -> v_type_uint32(OF2, [getPartitionLeader, payload | Path], TrUserData);
        #{payload := {getReplicaNodes, OF2}} -> v_type_string(OF2, [getReplicaNodes, payload | Path], TrUserData);
        #{payload := F2} -> mk_type_error(invalid_oneof, F2, [payload | Path]);
        _ -> ok
    end,
    lists:foreach(fun (seq) -> ok;
                      (payload) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
'v_msg_master.Request'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'master.Request'}, M, Path);
'v_msg_master.Request'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'master.Request'}, X, Path).

-compile({nowarn_unused_function,'v_msg_master.Response'/3}).
-dialyzer({nowarn_function,'v_msg_master.Response'/3}).
'v_msg_master.Response'(#{} = M, Path, TrUserData) ->
    case M of
        #{seq := F1} -> v_type_uint32(F1, [seq | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{payload := {registerReply, OF2}} -> 'v_msg_master.RegisterReply'(OF2, [registerReply, payload | Path], TrUserData);
        #{payload := {getPartitionLeaderReply, OF2}} -> 'v_msg_master.Address'(OF2, [getPartitionLeaderReply, payload | Path], TrUserData);
        #{payload := {getReplicaNodesReply, OF2}} -> 'v_msg_master.GetNodesReply'(OF2, [getReplicaNodesReply, payload | Path], TrUserData);
        #{payload := F2} -> mk_type_error(invalid_oneof, F2, [payload | Path]);
        _ -> ok
    end,
    lists:foreach(fun (seq) -> ok;
                      (payload) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
'v_msg_master.Response'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'master.Response'}, M, Path);
'v_msg_master.Response'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'master.Response'}, X, Path).

-compile({nowarn_unused_function,v_type_uint32/3}).
-dialyzer({nowarn_function,v_type_uint32/3}).
v_type_uint32(N, _Path, _TrUserData) when 0 =< N, N =< 4294967295 -> ok;
v_type_uint32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint32, unsigned, 32}, N, Path);
v_type_uint32(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint32, unsigned, 32}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.




gpb_version_as_string() ->
    "4.19.1".

gpb_version_as_list() ->
    [4,19,1].

gpb_version_source() ->
    "git".
